### ISSUE TITLE
DotNetty Remote Transport Issues with .NET Core 2.1

### ISSUE THREAD

**Issue by DaKaLKa** [akkadotnet/akka.net#3506]
I have a test application with 1 seed node and two service nodes.
After migrating to .NET Core 2.1, I have some  "Can't join seed-node" issues using Akka.net 1.3.6 / 1.3.8.  The software is build and executed in docker with official Microsoft .NET Core 2.1 Images (microsoft/dotnet:2.1-sdk and microsoft/dotnet:2.1-runtime). Sometimes the nodes get connected without problems, sometimes I have the "can't join seed-nodes"-problems without any changes. 
The problem appears on my local laptom and on our docker-server (and some other test-Systems).

The same application caused no problems running it on windows through Visual Studio. 
Migration back to ".NET Core 2.0" solved the problem for now. (Project-Settings and other microsoft/dotnet:2.0-docker-Images).

**Comment by Aaronontheweb** [comment]
Technically, everything we do should be working on .NET Core 2.1 since .NET Standard 1.6 can be consumed upstream. We'll investigate. Might be a DotNetty issue since v0.4.8 started using some of the unsafe APIs.

**Comment by xlegalles** [comment]
It may be also valid for Windows as our implementation does not work anymore since we moved to .NET Core 2.1. We still need to investigate but the problem is exactly the same: remote actors cannot join anymore. We tested both in Docker and out of container.

**Comment by xlegalles** [comment]
Forget my comment: it was not related to AKKA. So it means that we are able to use AKKA.Net with 2.1 under Windows.

**Comment by annymsMthd** [comment]
We are currently running a 1.3.8 cluster with .net core 2.1 in k8s with only a few minor issues.

**Comment by Lutando** [comment]
@annymsMthd  what were those minor issues?

**Comment by annymsMthd** [comment]
Sometimes we have a node that starts kicking out other nodes after we deploy even though it's not leader. It just starts marking nodes as down and even though they restart it just targets them again and marks them. When we reset the node that is doing the marking everything works. We only see this when we deploy though so it isn't a show stopper.

**Comment by Lutando** [comment]
We have a similar behavior. Might be worth investigating.

**Comment by Cephei** [comment]
Experiencing the same issue. Net core 2.1 on Linux. The problem is random ; restating often works

**Comment by Aaronontheweb** [comment]
Based on some of the quality issues we've had with DotNetty recently, I've been exploring a replacement for it built on Akka.Streams.

But that is a ways off still. In the short run, I'll look more closely at the .NET Core 2.1 issues you all have been reporting. Strong chance it's something fucked up with the runtime itself and DotNetty has to patch around it in order to get it to work. Wouldn't be the first time this has happened. Part of the price of being on the bleeding edge.

RE: the cluster issues. We'll look into that too - is that caused by nodes having connectivity problems or does this appear to be a 100% programmatic issue?

**Comment by mmisztal1980** [comment]
@Aaronontheweb I've examined my hocon multiple times (hocon below is the final configuration) and to be honest I don't see anything wrong with it. (keep in mind that it's been a while).

```hocon
  akka : {
    stdout-loglevel : DEBUG
    loglevel : INFO
    log-config-on-start : on
    loggers : ["Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog"]
    actor : {
      provider : cluster
      debug : {
        receive : on
        autoreceive : on
        lifecycle : on
        event-stream : on
        unhandled : on
      }
    }
    remote : {
      dot-netty : {
        tcp : {
          transport-class : "Akka.Remote.Transport.DotNetty.TcpTransport, Akka.Remote"
          transport-protocol : tcp
          hostname : 0.0.0.0
          public-hostname : core-cluster-svc
          port : 9000
        }
      }
    }
    cluster : {
      log-info : on
      seed-nodes : ["akka.tcp://System@core-cluster-svc-1:9000","akka.tcp://System@core-cluster-svc-2:9000","akka.tcp://System@core-cluster-svc:9000"]
      roles : [cluster-seed]
    }
  }
```

```yml
version: '3.4'

services:
  dmon-telemetry-db-dashboard:
    depends_on: 
      - dmon-telemetry-db
    image: docker.elastic.co/kibana/kibana:6.3.0
  dmon-telemetry-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
  core-cluster-svc:
    depends_on: 
      - dmon-telemetry-db
    image: core-cluster-svc
    build:
      context: .
      dockerfile: src/Core.Cluster.Service/Dockerfile
  core-cluster-svc-1:
    image: core-cluster-svc
    depends_on: 
      - core-cluster-svc
  core-cluster-svc-2:
    image: core-cluster-svc
    depends_on: 
      - core-cluster-svc
```

I've performed connectivity check between:
- core-cluster-svc & core-cluster-svc1
- core-cluster-svc & core-cluster-svc2

The checks have been completed via telnet:

I've attached to the running container via: `docker exec -it <core-cluster-svc_containerId> /bin/bash`

And then executed:

```bash
apt-get update
apt-get install telnet
telnet core-cluster-svc-1 9000
telnet core-cluster-svc-2 9000
```

Both connections were successful as I'd expect them to be, since docker-compose creates a docker-network with dns support.

**Comment by alexsandro-xpt** [comment]
@annymsMthd and @Lutando Are you have a code demo to test it?. I will run it under Kubernetes.

**Comment by mmisztal1980** [comment]
@Aaronontheweb 

I've set `akka.remote.dot-netty.tcp.log-transport = true` and set the overall logging level to `DEBUG`.

Here's the output I've captured:
[log.txt](https://github.com/akkadotnet/akka.net/files/2376739/log.txt)

```yml
version: '2.4'

services:
  dmon-telemetry-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
  dmon-telemetry-db-dashboard:
    depends_on: 
      dmon-telemetry-db:
          condition: service_healthy
    image: docker.elastic.co/kibana/kibana:6.3.0
  core-cluster-svc: # This is an equivalent of Lighthouse running under .net core 2.1. Instance 1/3
    depends_on: 
      dmon-telemetry-db:
          condition: service_healthy
    image: core-cluster-svc
    build:
      context: .
      dockerfile: src/Core.Cluster.Service/Dockerfile
  core-cluster-svc-1: # Instance 2/3
    image: core-cluster-svc
    depends_on: 
      - core-cluster-svc
  core-cluster-svc-2: # Instance 3/3
    image: core-cluster-svc
    depends_on: 
      - core-cluster-svc
```

Hope that helps a bit.
